### ISSUE TITLE
Need a release of example-scalafix-rule

### ISSUE THREAD

**Issue by mlachkar-da** [scalacenter/example-scalafix-rule#10]
We need a release of 0.10.0, but it's failing because of this: 
```
Error:  gpg: no default secret key: unusable secret key
Error:  gpg: signing failed: unusable secret key
Error:  java.lang.RuntimeException: Failure running 'gpg --batch --passphrase *** --detach-sign --armor --use-agent --output /home/runner/work/example-scalafix-rule/example-scalafix-rule/scalafix/rules/target/scala-2.11/example-scalafix-rule_2.11-2.0.0.pom.asc /home/runner/work/example-scalafix-rule/example-scalafix-rule/scalafix/rules/target/scala-2.11/example-scalafix-rule_2.11-2.0.0.pom'.  Exit code: 2
```

Can you help with that @julienrf @sjrd  (cc @bjaglin) ?
Thank you !

**Comment by julienrf** [comment]
Weird :thinking: 

I’ve created new secrets and now it works fine. I’ve run the workflow again and the rule should be on its way to Maven Central.

BTW, I suggest updating your GitHub workflows to use `setup-java` and `cache: sbt` to avoid re-downloading the dependencies of the project over and over.

**Comment by mlachkar** [comment]
thank you!

**Comment by julienrf** [comment]
Do you have the right to update the secrets? https://github.com/scalacenter/example-scalafix-rule/settings/secrets/actions

**Comment by mlachkar** [comment]
No I don't.

**Comment by julienrf** [comment]
OK, that should be fixed now, can you confirm?

**Comment by mlachkar** [comment]
I confirm. Thank a lot. If it's ok, I may need the same access on scalafix (acces to secrets), but nothing urgent.

**Comment by julienrf** [comment]
Sure!

**Comment by bjaglin** [comment]
Thanks @julienrf! While we are at it, there are other repos that are related to scalafix, so maybe you can extend the rights to them? See list in https://github.com/scalacenter/scalafix/issues/1616#issue-1264294460.

**Comment by julienrf** [comment]
Done :)
