### ISSUE TITLE
Failure on publish

### ISSUE THREAD

**Issue by bjaglin** [scalacenter/example-scalafix-rule#11]
https://github.com/scalacenter/example-scalafix-rule/actions/runs/5164023440/jobs/9302676013

> Error:  gpg: no default secret key: No secret key
> Error:  gpg: signing failed: No secret key
> Error:  java.lang.RuntimeException: Failure running 'gpg --batch --passphrase *** --detach-sign --armor --use-agent --output /home/runner/work/example-scalafix-rule/example-scalafix-rule/scalafix/rules/target/scala-2.12/example-scalafix-rule_2.12-3.0.0.pom.asc /home/runner/work/example-scalafix-rule/example-scalafix-rule/scalafix/rules/target/scala-2.12/example-scalafix-rule_2.12-3.0.0.pom'.  Exit code: 2

**Comment by bjaglin** [comment]
@julienrf I remember I ran into a similar problem in some scalacenter repo a while ago, is that something you could help with? Thanks!

**Comment by julienrf** [comment]
I am not sure about the cause of the issue. The PGP key is supposed to expire in 2024.

**Comment by bjaglin** [comment]
After bumping sbt-ci-release to the latest version, the publishing was successful.

@julienrf what's the process for getting Scala Center Steward to keep that repo up to date?

**Comment by julienrf** [comment]
You need to add yourself to the `repos.md` file in this repo: https://github.com/scalacenter/steward. I just did it for example-scalafix-rule.
